In [1]:
"""
Unit Converter Program
This program converts length, weight, and volume units.
Author: Bandita Jaiswar
"""

def meters_to_feet(m):
    """Convert meters to feet"""
    return m * 3.28084

def kg_to_pounds(kg):
    """Convert kilograms to pounds"""
    return kg * 2.20462

def liters_to_gallons(l):
    """Convert liters to gallons"""
    return l * 0.264172

def main():
    try:
        print("1. Length (meters to feet)")
        print("2. Weight (kg to pounds)")
        print("3. Volume (liters to gallons)")

        choice = int(input("Choose conversion type (1-3): "))
        value = float(input("Enter value: "))

        if choice == 1:
            print("Result:", meters_to_feet(value))
        elif choice == 2:
            print("Result:", kg_to_pounds(value))
        elif choice == 3:
            print("Result:", liters_to_gallons(value))
        else:
            print("Invalid choice")

    except ValueError:
        print("Please enter valid numeric input")

main()

1. Length (meters to feet)
2. Weight (kg to pounds)
3. Volume (liters to gallons)
Choose conversion type (1-3): 2
Enter value: 12
Result: 26.455439999999996


In [2]:
"""
List Operations Program
"""

def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers)

def find_max(numbers):
    return max(numbers)

def find_min(numbers):
    return min(numbers)

try:
    user_input = input("Enter numbers separated by space: ")
    numbers = list(map(float, user_input.split()))

    print("1. Sum")
    print("2. Average")
    print("3. Max")
    print("4. Min")

    choice = int(input("Choose operation: "))

    if choice == 1:
        print("Sum:", calculate_sum(numbers))
    elif choice == 2:
        print("Average:", calculate_average(numbers))
    elif choice == 3:
        print("Max:", find_max(numbers))
    elif choice == 4:
        print("Min:", find_min(numbers))
    else:
        print("Invalid choice")

except ValueError:
    print("Invalid input")

Enter numbers separated by space: 2
1. Sum
2. Average
3. Max
4. Min
Choose operation: 2
Average: 2.0


In [3]:
def every_other_element(lst):
    return lst[::2]

def reverse_list(lst):
    return lst[::-1]

def remove_first_last(lst):
    return lst[1:-1]

def first_n_elements(lst, n):
    return lst[:n]

def last_n_elements(lst, n):
    return lst[-n:]

# Example test
sample = [1,2,3,4,5,6,7,8]
print("Every other:", every_other_element(sample))
print("Reversed:", reverse_list(sample))

Every other: [1, 3, 5, 7]
Reversed: [8, 7, 6, 5, 4, 3, 2, 1]


In [4]:
import numpy as np

In [5]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
a = np.arange(10)
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [8]:
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)

print("A * A_inv:")
print(np.dot(A, A_inv))

A * A_inv:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
import time

# Python list
start = time.time()
lst = list(range(1000000))
s = [x*2 for x in lst]
print("Python time:", time.time() - start)

# NumPy
start = time.time()
arr = np.arange(1000000)
arr2 = arr * 2
print("NumPy time:", time.time() - start)

Python time: 0.08791542053222656
NumPy time: 0.009259462356567383
